.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MODULES_LOGGER" "1" "November 2012" "" ""
.
.SH "NAME"
\fBmodules_logger\fR \- logs an environment modules operation to a central datastore
.
.SH "SYNOPSIS"
\fBmodules_logger\fR \fIusername\fR \fIoperation\fR [parameters\.\.\.]
.
.SH "DESCRIPTION"
modules_logger records a module operation to a central datastore based on the command\-line parameters\. Normally this shouldn\'t be invoked directly, but is instead invoked based on a modified module(1) function in the modules\.sh profile file:
.
.IP "" 4
.
.nf

module() {
    ARGS=$*;
    modules_logger $USER $ARGS;
    eval `/usr/bin/modulecmd sh $ARGS`;
}
.
.fi
.
.IP "" 0
.
.P
Each operation is logged to a MongoDB database based on the parameters in modules_logger\.conf(5)\.
.
.SH "AUTHOR"
Adam DeConinck \fIajdecon@ajdecon\.org\fR
.
.SH "SEE ALSO"
modules_usage(1), modules_logger\.conf(5)
