#!/usr/bin/python

import sys
import pymongo
import datetime
import re
import ConfigParser

def print_usage():
    print "USAGE:   %s username operation [modulename]" % (sys.argv[0])

# mongodb keys can't contain dots
# POTENTIALLY BAD ASSUMPTION: module names won't contain commas
def encode_dots(key):
    return re.sub(r'\.',',',key)

# Get command line arguments
if len(sys.argv)<2:
    print_usage()
    sys.exit(1)
username = sys.argv[1].lower()
operation = sys.argv[2].lower()
if len(sys.argv)==4:
    modulename = encode_dots(sys.argv[3])
else:
    modulename = ""

# Set up DB connection
Config = ConfigParser.ConfigParser()
Config.read("/etc/modules_logger.conf")
server=Config.get("mongodb","server")
port=Config.get("mongodb","port")
dbname=Config.get("mongodb","db")
connection = pymongo.Connection(server,int(port))
db = connection[dbname]
users = db.users
logs = db.logs

# Log the request
now = datetime.datetime.utcnow()
l = { "username": username,
      "operation": operation,
      "args": ' '.join(sys.argv[3:]),
      "date": now }
logs.insert(l)

# Accumulate load operations
if operation=="load":

    # Get the user, if they exist; else create
    u = users.find_one({"username": username})
    if not u:
        u_new = { "username": username }
        users.insert(u_new)
        u = users.find_one({"username": username})
    try:
        u[modulename]["count"]+=1
    except KeyError:
        u[modulename] = {"count":1}
#        u[modulename]["count"]=1
    u[modulename]["last_loaded"]=now
    users.save(u)


